azs:
- name: z1
- name: z2
- name: z3
compilation:
  az: z1
  network: webapp-network
  reuse_compilation_vms: true
  vm_type: default
  workers: 5
disk_types:
- disk_size: 1024
  name: default
networks:
- name: webapp-network
  subnets:
  - azs:
    - z1
    - z2
    - z3
    dns:
    - 8.8.8.8
    gateway: 10.244.1.1
    range: 10.244.1.0/24
    reserved: []
    static:
    - 10.244.1.2
  type: manual
vm_types:
- name: default
